spring:
    application:
        name: client

eureka:
    client:
        serviceUrl:
            defaultZone: "http://localhost:${registry.port:8761}/eureka/"
        healthcheck:
            enabled: true
    instance:
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
    level:
        com:
            netflix: debug
