spring:
    application:
        name: server
server:
    port: 9090

eureka:
    client:
        serviceUrl:
            defaultZone: "http://localhost:${registry.port:8761}/eureka/"
        healthcheck:
            enabled: true
        eureka-service-url-poll-interval-seconds: 15
logging:
    level:
        com:
            netflix: debug
feign:
    client:
        config:
            default:
                connectTimeout: 10000
                readTimeout: 10000
