spring:
    application:
        name: server
server:
    port: 9090

eureka:
    client:
        serviceUrl:
            defaultZone: http://${registry.host:eureka-test}:${registry.port:8761}/eureka/
        healthcheck:
            enabled: true
        eureka-service-url-poll-interval-seconds: 1
logging:
    level:
        com:
            netflix: debug
