spring:
    application:
        name: eureka-serviceregistry
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
        region: default
logging:
    level:
        com:
            netflix: debug
